// Generated from contracts/src/BatchSettler.sol. Run npm run contracts:abi.
export const batchSettlerAbi = [
  {"type":"constructor","inputs":[{"name":"tokenAddress","type":"address","internalType":"address"},{"name":"allowedFacilitators","type":"address[]","internalType":"address[]"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"MAX_BATCH_SIZE","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"PAYMENT_TYPEHASH","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"commitment","inputs":[{"name":"payment","type":"tuple","internalType":"struct BatchSettler.Payment","components":[{"name":"paymentId","type":"bytes32","internalType":"bytes32"},{"name":"salt","type":"bytes32","internalType":"bytes32"},{"name":"payer","type":"address","internalType":"address"},{"name":"seller","type":"address","internalType":"address"},{"name":"treasury","type":"address","internalType":"address"},{"name":"gross","type":"uint256","internalType":"uint256"},{"name":"sellerAmount","type":"uint256","internalType":"uint256"},{"name":"feeAmount","type":"uint256","internalType":"uint256"},{"name":"validAfter","type":"uint256","internalType":"uint256"},{"name":"validBefore","type":"uint256","internalType":"uint256"},{"name":"nonce","type":"bytes32","internalType":"bytes32"},{"name":"v","type":"uint8","internalType":"uint8"},{"name":"r","type":"bytes32","internalType":"bytes32"},{"name":"s","type":"bytes32","internalType":"bytes32"}]}],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"facilitators","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"settleBatch","inputs":[{"name":"payments","type":"tuple[]","internalType":"struct BatchSettler.Payment[]","components":[{"name":"paymentId","type":"bytes32","internalType":"bytes32"},{"name":"salt","type":"bytes32","internalType":"bytes32"},{"name":"payer","type":"address","internalType":"address"},{"name":"seller","type":"address","internalType":"address"},{"name":"treasury","type":"address","internalType":"address"},{"name":"gross","type":"uint256","internalType":"uint256"},{"name":"sellerAmount","type":"uint256","internalType":"uint256"},{"name":"feeAmount","type":"uint256","internalType":"uint256"},{"name":"validAfter","type":"uint256","internalType":"uint256"},{"name":"validBefore","type":"uint256","internalType":"uint256"},{"name":"nonce","type":"bytes32","internalType":"bytes32"},{"name":"v","type":"uint8","internalType":"uint8"},{"name":"r","type":"bytes32","internalType":"bytes32"},{"name":"s","type":"bytes32","internalType":"bytes32"}]}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"token","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract IERC20"}],"stateMutability":"view"},
  {"type":"event","name":"PaymentSettled","inputs":[{"name":"paymentId","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"payer","type":"address","indexed":true,"internalType":"address"},{"name":"nonce","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"itemIndex","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"seller","type":"address","indexed":false,"internalType":"address"},{"name":"treasury","type":"address","indexed":false,"internalType":"address"},{"name":"gross","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"sellerAmount","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"feeAmount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"error","name":"InvalidBatch","inputs":[]},
  {"type":"error","name":"InvalidConfiguration","inputs":[]},
  {"type":"error","name":"InvalidPayment","inputs":[]},
  {"type":"error","name":"PrincipalRetained","inputs":[]},
  {"type":"error","name":"ReentrancyGuardReentrantCall","inputs":[]},
  {"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address","internalType":"address"}]},
  {"type":"error","name":"UnauthorizedFacilitator","inputs":[]},
] as const;
